### ISSUE TITLE
旧项目迁移到core环境

### ISSUE THREAD

**Issue by CalabashSun** [caozhiyuan/FastDFSNetCore#1]
代码基本没动用的

{System.InvalidCastException: Unable to cast object of type 'System.Int32' to type 'System.Int64'.
   at FastDFS.Core.UPLOAD_FILE.GetRequest(Object[] paramList)
   at FastDFS.Core.FastDFSClient.UploadFile(StorageNode storageNode, Byte[] contentByte, String fileExt)
 
遇到了这个问题

**Comment by caozhiyuan** [comment]
@CalabashSun 
你用NuGet包可能不是我的 我的包是FastDFSNetCore
Core环境最好用异步的  同步的并发情况下性能差 
这里面有用法 你试下 
https://github.com/caozhiyuan/FastDFSNetCore/blob/master/src/FastDFS.Test/Program.cs

**Comment by CalabashSun** [comment]
恩 刚对比了，下发现了 谢谢帮助
