### ISSUE TITLE
上传的文件没有扩展名，FastDFSClient.UploadFileAsync第三个参数怎么写？

### ISSUE THREAD

**Issue by andy65007** [caozhiyuan/FastDFSNetCore#14]
报错如下：
Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at FastDFS.Client.UPLOAD_FILE.GetRequest(Object[] paramList)
   at FastDFS.Client.FastDFSClient.UploadFileAsync(StorageNode storageNode, Stream contentStream, String fileExt)

   at FastDFS.Client.FastDFSClient.UploadFileAsync(StorageNode storageNode, Byte[] contentByte, String fileExt)

**Comment by caozhiyuan** [comment]
must need fileExt.

**Comment by andy65007** [comment]
是fastdfs需要，还是fastdfsnetcore需要？

**Comment by caozhiyuan** [comment]
fixed @andy65007
